# Generated by Django 6.1.1 on 2026-09-14 16:16

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('computadora', 'Computadora'), ('laptop', 'Laptop'), ('proyector', 'Proyector'), ('impresora', 'Impresora'), ('access_point', 'Access Point'), ('switch', 'Switch')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='activo', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
                'permissions': [('puede_asignar_equipo', 'Puede asignar equipo a responsable')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEquipo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('computadora', 'Computadora'), ('laptop', 'Laptop'), ('proyector', 'Proyector'), ('impresora', 'Impresora'), ('access_point', 'Access Point'), ('switch', 'Switch')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(db_index=True, max_length=100)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='activo', max_length=20)),
                ('fecha_registro', models.DateField(blank=True, editable=False)),
                ('observaciones', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical equipo',
                'verbose_name_plural': 'historical equipos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edificio', models.CharField(blank=True, max_length=100)),
                ('salon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=255)),
                ('valor_nuevo', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='inventario.equipo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
