# Generated by Django 6.1.1 on 2026-09-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tipo_otro',
            field=models.CharField(blank=True, help_text='Especifique el tipo si seleccionó "Otro"', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='tipo_otro',
            field=models.CharField(blank=True, help_text='Especifique el tipo si seleccionó "Otro"', max_length=100),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Nivel superior (ej: un Salón pertenece a una Etapa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sububicaciones', to='inventario.ubicacion', verbose_name='Pertenece a'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('sede', 'Sede'), ('etapa', 'Etapa'), ('salon', 'Salón'), ('laboratorio', 'Laboratorio'), ('oficina', 'Oficina'), ('otro', 'Otro')], default='salon', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('laptop', 'Laptop'), ('proyector', 'Proyector'), ('impresora', 'Impresora'), ('access_point', 'Access Point'), ('switch', 'Switch'), ('otro', 'Otro (especificar)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalequipo',
            name='tipo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('laptop', 'Laptop'), ('proyector', 'Proyector'), ('impresora', 'Impresora'), ('access_point', 'Access Point'), ('switch', 'Switch'), ('otro', 'Otro (especificar)')], max_length=20),
        ),
    ]
