# Generated by Django 6.1.1 on 2026-09-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_equipo_tipo_otro_historicalequipo_tipo_otro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='aula',
            field=models.CharField(blank=True, help_text='Aula dentro de la ubicación. Ej: 01, 05, 13', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='aula',
            field=models.CharField(blank=True, help_text='Aula dentro de la ubicación. Ej: 01, 05, 13', max_length=10),
        ),
    ]
