# Generated by Django 6.1.1 on 2026-09-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_equipo_aula_historicalequipo_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='almacenamiento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Almacenamiento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='procesador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Memoria RAM'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='so',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sistema operativo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor económico del equipo (no obligatorio)', max_digits=12, null=True, verbose_name='Valor ($)'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='almacenamiento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Almacenamiento'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='procesador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='ram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Memoria RAM'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='so',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sistema operativo'),
        ),
        migrations.AddField(
            model_name='historicalequipo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor económico del equipo (no obligatorio)', max_digits=12, null=True, verbose_name='Valor ($)'),
        ),
    ]
