# Generated by Django 6.1.1 on 2026-09-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa_ayuda', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='area',
            field=models.CharField(blank=True, help_text='Salón / área donde ocurrió la falla', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='contacto',
            field=models.CharField(blank=True, help_text='Email o teléfono de contacto del reportero', max_length=100),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='nombre_reportero',
            field=models.CharField(blank=True, help_text='Nombre de quien reporta (si no es usuario del sistema)', max_length=150),
        ),
    ]
