# Generated by Django 6.1.1 on 2026-09-14 17:42

from django.db import migrations, models


def migrar_consulta_a_tecnico(apps, schema_editor):
    User = apps.get_model('usuarios', 'User')
    User.objects.filter(rol='consulta').update(rol='tecnico')


def retroceder(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico')], default='tecnico', max_length=10),
        ),
        migrations.RunPython(migrar_consulta_a_tecnico, retroceder),
    ]
