# Generated by Django 6.1.1 on 2026-09-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=15)),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=15)),
                ('historial', models.TextField(blank=True, help_text='Registro de pasos realizados')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='inventario.equipo')),
            ],
            options={
                'ordering': ['fecha_programada'],
                'permissions': [('puede_programar_mantenimiento', 'Puede programar mantenimientos')],
            },
        ),
    ]
